# Generated by Django 5.1.5 on 2025-01-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='yandex_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
