# Generated by Django 5.1.4 on 2025-01-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_category_remove_course_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(choices=[('Алгебра', 'Алгебра'), ('Английский язык', 'Английский язык'), ('Биология', 'Биология'), ('География', 'География'), ('Геометрия', 'Геометрия'), ('Информатика', 'Информатика'), ('История', 'История'), ('Литература', 'Литература'), ('Математика', 'Математика'), ('Обществознание', 'Обществознание'), ('Русский язык', 'Русский язык'), ('Физика', 'Физика'), ('Химия', 'Химия')], max_length=100),
        ),
    ]
