# Generated by Django 5.1.4 on 2025-01-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_created_at_course_duration_course_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='full_text',
            field=models.TextField(default=1, help_text='Полный текст курса'),
            preserve_default=False,
        ),
    ]
