# Generated by Django 5.1.4 on 2025-01-13 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_full_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.CharField(blank=True, max_length=200, verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=50, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='full_text',
            field=models.TextField(help_text='Полный текст курса', verbose_name='Полный текст'),
        ),
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11')], verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='main/img/default_course_image.jpg', null=True, upload_to='courses_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(choices=[('Алгебра', 'Алгебра'), ('Английский язык', 'Английский язык'), ('Биология', 'Биология'), ('География', 'География'), ('Геометрия', 'Геометрия'), ('Информатика', 'Информатика'), ('История', 'История'), ('Литература', 'Литература'), ('Математика', 'Математика'), ('Обществознание', 'Обществознание'), ('Русский язык', 'Русский язык'), ('Физика', 'Физика'), ('Химия', 'Химия')], max_length=100, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
