# Generated by Django 5.1.4 on 2025-01-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_course_duration_course_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='presentation',
            field=models.FileField(blank=True, null=True, upload_to='courses_presentations/', verbose_name='Презентация'),
        ),
        migrations.AddField(
            model_name='course',
            name='text_file',
            field=models.FileField(blank=True, null=True, upload_to='courses_texts/', verbose_name='Текстовый файл'),
        ),
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='courses_videos/', verbose_name='Видеоролик'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=150, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
