# Generated by Django 5.1.4 on 2025-01-19 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_presentation_course_text_file_course_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='presentation',
        ),
        migrations.RemoveField(
            model_name='course',
            name='text_file',
        ),
        migrations.RemoveField(
            model_name='course',
            name='video',
        ),
    ]
