# Generated by Django 5.1.4 on 2025-01-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_course_presentation_remove_course_text_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='materials',
            field=models.FileField(blank=True, null=True, upload_to='course_materials/', verbose_name='Материалы'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Описание'),
        ),
    ]
