# Generated by Django 5.1.4 on 2025-01-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение для курса', null=True, upload_to='courses_images/', verbose_name='Изображение курса'),
        ),
    ]
