# Generated by Django 5.1.4 on 2025-01-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(help_text='Загрузите изображение для курса', null=True, upload_to='courses_images/', verbose_name='Изображение курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.CharField(max_length=200, verbose_name='Тэги'),
        ),
    ]
